[formatter.fourmolu]
command = "fourmolu"
options = ["--mode", "inplace"]
includes = ["src/**/*.hs", "test/**/*.hs", "tests/**/*.hs"]

[formatter.elm-format]
command = "elm-format"
options = ["--yes"]
includes = ["elm-app/src/**/*.elm"]
