name: 'Setup Nix + devenv'
description: 'Install Nix, configure Cachix, install devenv'

inputs:
  cachix-auth-token:
    description: 'Cachix auth token'
    required: true
  github-token:
    description: 'GitHub token for Nix'
    required: true

runs:
  using: 'composite'
  steps:
    - uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ inputs.github-token }}

    - uses: cachix/cachix-action@v16
      with:
        name: palikkaharrastajat
        authToken: ${{ inputs.cachix-auth-token }}
        extraPullNames: devenv

    - name: Install devenv
      shell: bash
      run: nix profile install "github:cachix/devenv/v2.1.2"
